name: on_network
description: "The ON Network Project."
publish_to: 'none'

version: 2.0.0+11

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- LOKALİZASYON (FORMATLAMA) PAKETİ ---
  flutter_localizations:
    sdk: flutter
  # --- BİTTİ ---

  cupertino_icons: ^1.0.8

  # === FIREBASE (BİRBİRİYLE UYUMLU STABİL VERSİYONLAR) ===
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.0.2
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  firebase_performance: ^0.10.0+5
  # --- BİTTİ ---

  # === RIVERPOD (KODUN YAZILDIĞI STABİL VERSİYON) ===
  flutter_riverpod: ^2.5.1
  # --- BİTTİ ---

  # === DİĞER PAKETLER ===
  google_mobile_ads: ^5.1.0
  flutter_local_notifications: ^17.1.2
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  webview_flutter: ^4.8.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  nanoid: ^1.0.0
  google_sign_in: ^6.2.1
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0 # <--- YENİ EKLENDİ
  path_provider: ^2.1.3 # <--- BU YENİ PAKET
  firebase_remote_config: ^5.0.0 # Sunucu ayarlarını okumak için
  package_info_plus: ^8.0.0 # Uygulamanın kendi versiyonunu okumak için
  app_tracking_transparency: ^2.0.4 # <-- IOS İÇİN EKLENDİ
  flutter_svg: ^2.0.10
  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/splash_animation.gif
    - assets/images/google_logo.png
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0D0D2E"
  adaptive_icon_foreground: "assets/images/logo.png"